language: node_js
node_js:
  - 13

services:
  - docker
  
# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"
script:
  #Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  #tagging
  - docker tag udagram-api-feed michaelrafaillo/udagram-api-feed:v1
  - docker tag udagram-api-user michaelrafaillo/udagram-api-user:v1
  - docker tag udagram-frontend michaelrafaillo/udagram-frontend:local
  - docker tag udagram-reverseproxy michaelrafaillo/reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push michaelrafaillo/udagram-api-feed:v1
  - docker push michaelrafaillo/udagram-api-user:v1
  - docker push michaelrafaillo/udagram-frontend:local
  - docker push michaelrafaillo/reverseproxy:v1
  
